#!/bin/bash
# Demonstrate with concurrent USER and ATTACKER

PATH="$(dirname "$0")/../src:$PATH"

# OWNER
SECRET="!!!secret!!!"

# PROXY
read IPC_QUEUE IPC_QUEUEID IPC_SEM1ID IPC_SEM2ID < <( smq_create.py )
socat UNIX-LISTEN:proxy,fork,mode=777 EXEC:"smq_receive.py $IPC_QUEUE "<( #subprocess IPC send
  while smq_send.py $IPC_QUEUE socat <<< "$(mcrypt -q -k XYZ <<< "$SECRET" | base64 -w0)" ; do : ; done
  ),stderr &
PROXY=$!
trap "ipcrm -q $IPC_QUEUEID -s $IPC_SEM1ID -s $IPC_SEM2ID;kill $PROXY" exit
sleep 1

# USER
for i in {1..30};do echo USER GOT $(socat - UNIX-CONNECT:proxy | base64 -d | mdecrypt -q -k XYZ) ; done &
USER=$!

sleep 1

# ATTACKER
for i in {1..30};do echo ATTACKER GOT $(smq_receive.py $IPC_QUEUE | base64 -d | mdecrypt -q -k XYZ) ; done &
ATTACKER=$!
{ sleep 15; kill $ATTACKER ; } &

wait $USER $ATTACKER
