#!/bin/bash
#Demonstrate the use of mcrypt + base64 for the message body

for i in {1..5};do
echo '!!!secret!!!' | mcrypt -q -k XYZ | base64 -w0 | tee >(cat >&2) | base64 -d | mdecrypt -q -k XYZ >&2
done
